// <auto-generated />
using System;
using ControleGastosResidenciais.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleGastosResidenciais.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326165645_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ControleGastosResidenciais.Api.Models.Categoria", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dataExclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("excluido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("finalidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("codigo");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("ControleGastosResidenciais.Api.Models.Pessoa", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dataExclusao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("excluido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("codigo");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("ControleGastosResidenciais.Api.Models.Transacao", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("codCategoria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("codPessoa")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("dataAlteracao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("dataExclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<bool>("excluido")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tipo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("codigo");

                    b.HasIndex("codCategoria");

                    b.HasIndex("codPessoa");

                    b.ToTable("Transacao");
                });

            modelBuilder.Entity("ControleGastosResidenciais.Api.Models.Transacao", b =>
                {
                    b.HasOne("ControleGastosResidenciais.Api.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("codCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ControleGastosResidenciais.Api.Models.Pessoa", null)
                        .WithMany()
                        .HasForeignKey("codPessoa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
